
ALTER TABLE producto  ADD COLUMN identidad VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN trx_tipo_consulta VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN trx_tipo_pago VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN trx_tipo_reverso VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN trx_tipo_aux VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN comision_rubro VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN referencia_titulo VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN referencia_tipo_dato VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN referencia_longitud VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN tipo_pago VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN info_add VARCHAR(200); 
ALTER TABLE producto  ADD COLUMN recibo_titulo VARCHAR(200); 